#!/usr/bin/env python3
"""
install.py — Bootstrap a new slope for the avachain pipeline.

Reads slopes/<name>/slope_config.toml and:
  1. Creates the expected directory structure
  2. Finds the closest WRF grid cell and aspect variant; writes result back to TOML
  3. Generates slopes/<name>/master_config.ini (SNOWPACK physics config)
  4. Generates slopes/<name>/run_snowpack.sh
  5. Generates run_<name>.sh at the project root
  6. Prints the crontab line

Usage:
    python install.py slopes/little_prof/slope_config.toml
    python install.py --slope little_prof
    python install.py --list
"""

from __future__ import annotations

import argparse
import math
import re
import stat
import sys
import tomllib
from pathlib import Path

# ---------------------------------------------------------------------------
# SNOWPACK master_config.ini template
# Contains all common physics settings.  Per-cluster paths (METEOPATH,
# SNOWPATH, STATION1, SNOWFILE1) are set in the per-cluster ini generated
# by run_snowpack.sh via IMPORT_BEFORE = <this file>.
# COORDPARAM 10T matches the CAIC operational SNOWPACK configuration.
# ---------------------------------------------------------------------------

_MASTER_INI_TEMPLATE = """\
; master_config.ini — {display_name}
; Generated by install.py from slopes/{slope_name}/slope_config.toml.
; Contains SNOWPACK physics settings shared by all clusters.
; Per-cluster paths are provided via IMPORT_BEFORE in run_snowpack.sh.

[GENERAL]
BUFFER_SIZE = 370
BUFF_BEFORE = 1.5

[GENERATORS]
PSUM_PH::GENERATORS          = PRECSPLITTING
PSUM_PH::PRECSPLITTING::SNOW = 274.35
PSUM_PH::PRECSPLITTING::TYPE = THRESH

[INPUT]
TIME_ZONE  = 0
COORDSYS   = UTM
COORDPARAM = 10T

[INPUTEDITING]
*::ARG1::ALGORITHM = CST
*::ARG1::PARAM     = TSG
*::ARG1::VALUE     = 273.15
*::EDIT1           = CREATE

[INTERPOLATIONS1D]
PSUM::ARG1::PERIOD = 900
PSUM::RESAMPLE1    = ACCUMULATE

[OUTPUT]
TIME_ZONE            = 0
METEO                = SMET
EXPERIMENT           = res
TS_WRITE             = TRUE
TS_FORMAT            = SMET
TS_START             = 0.0
TS_DAYS_BETWEEN      = 0.25
PROFILE_FORMAT       = PRO
PROF_WRITE           = TRUE
PROF_START           = 0.0
PROF_DAYS_BETWEEN    = 0.25
PROF_AGE_OR_DATE     = DATE
OUT_STAB             = TRUE
OUT_HEAT             = TRUE
OUT_SW               = TRUE
OUT_LW               = TRUE
OUT_MASS             = TRUE
OUT_T                = TRUE
HAZ_WRITE            = TRUE
HAZARD_STEPS_BETWEEN = 2
PRECIP_RATES         = TRUE

[SNOWPACK]
ATMOSPHERIC_STABILITY      = NEUTRAL
CALCULATION_STEP_LENGTH    = 15
CANOPY                     = FALSE
CHANGE_BC                  = FALSE
ENFORCE_MEASURED_SNOW_HEIGHTS = TRUE
HEIGHT_OF_METEO_VALUES     = 2
HEIGHT_OF_WIND_VALUE       = 10
MEAS_TSS                   = FALSE
ROUGHNESS_LENGTH           = 0.002
SNP_SOIL                   = FALSE
SW_MODE                    = INCOMING

[SNOWPACKADVANCED]
ADJUST_HEIGHT_OF_METEO_VALUES        = true
ADJUST_HEIGHT_OF_WIND_VALUE          = true
ALBEDO_AGING                         = true
ALBEDO_AVERAGE_SCHMUCKI              = ALL_DATA
ALBEDO_PARAMETERIZATION              = LEHNING_2
ALLOW_ADAPTIVE_TIMESTEPPING          = TRUE
ALLOW_FREEZING_RAIN                  = true
ALPINE3D                             = false
COMBINE_ELEMENTS                     = true
DETECT_GRASS                         = false
ENFORCE_MEASURED_SNOW_HEIGHTS        = TRUE
FORCE_RH_WATER                       = true
HARDNESS_PARAMETERIZATION            = MONTI
HEIGHT_NEW_ELEM                      = 0.02
HN_DENSITY                           = PARAMETERIZED
HN_DENSITY_PARAMETERIZATION          = LEHNING_NEW
HOAR_DENSITY_BURIED                  = 125.
HOAR_DENSITY_SURF                    = 100.
HOAR_MIN_SIZE_BURIED                 = 2.
HOAR_MIN_SIZE_SURF                   = 0.5
HOAR_THRESH_RH                       = 0.97
HOAR_THRESH_TA                       = 1.2
HOAR_THRESH_VW                       = 3.5
LB_COND_WATERFLUX                    = FREEDRAINAGE
METAMORPHISM_MODEL                   = DEFAULT
MINIMUM_L_ELEMENT                    = 0.0025
MIN_DEPTH_SUBSURF                    = 0.07
NEW_SNOW_GRAIN_SIZE                  = 0.3
NUMBER_SLOPES                        = 5
PERP_TO_SLOPE                        = false
RESEARCH                             = true
SNOW_ALBEDO                          = PARAMETERIZED
SNOW_EROSION                         = false
SNOW_REDISTRIBUTION                  = false
STRENGTH_MODEL                       = DEFAULT
SW_ABSORPTION_SCHEME                 = MULTI_BAND
THRESH_RAIN                          = 1.2
THRESH_RH                            = 0.5
VARIANT                              = DEFAULT
VISCOSITY_MODEL                      = DEFAULT
WATERTRANSPORTMODEL_SNOW             = BUCKET
WATERTRANSPORTMODEL_SOIL             = BUCKET
WIND_SCALING_FACTOR                  = 1.0
"""

# ---------------------------------------------------------------------------
# Shell script templates
# ---------------------------------------------------------------------------

_RUN_SNOWPACK_TEMPLATE = """\
#!/bin/bash
# run_snowpack.sh — Run SNOWPACK on all {display_name} cluster .smet files.
# Generated by install.py from slopes/{slope_name}/slope_config.toml
#
# Usage:
#   ./run_snowpack.sh                          # full season (default dates)
#   ./run_snowpack.sh 2025-11-26 2026-04-15   # explicit start/end (YYYY-MM-DD)
#
# On first run:  each cluster gets a copy of template.sno as initial conditions.
# On reruns:     each cluster restarts from its own _res.sno (written by SNOWPACK).

# --- Paths ---
SNOWPACK_BIN={snowpack_bin}
export LD_LIBRARY_PATH=${{LD_LIBRARY_PATH:-}}:{snowpack_lib}

REPO_DIR={project_dir}
SLOPE_DIR=${{SLOPE_DIR:-{slope_dir}}}
SMET_DIR=${{SMET_DIR:-$REPO_DIR/outputs/smet}}
SNOW_IN_DIR=$SLOPE_DIR/input/snow
OUTPUT_DIR=$SLOPE_DIR/output
MASTER_CFG=$REPO_DIR/slopes/{slope_name}/config/master_config.ini
TEMPLATE_SNO=$SNOW_IN_DIR/template.sno

# --- Date range ---
first_smet=("$SMET_DIR"/cluster_*.smet)
if [[ -n "${{1:-}}" ]]; then
    BDATE="${{1}}"
    [[ "$BDATE" != *T* ]] && BDATE="${{BDATE}}T18:00"
else
    BDATE=$(awk '/^\\[DATA\\]/{{found=1; next}} found{{print $1; exit}}' "${{first_smet[0]}}")
fi
EDATE="${{2:-{season_end}}}T18:00"

# Optional: run only specific clusters (plain text or reinit_stats JSON)
CLUSTERS_FILE="${{3:-}}"

MAX_JOBS={max_jobs}

# --- Sanity checks ---
for f in "$SNOWPACK_BIN" "$MASTER_CFG" "$TEMPLATE_SNO"; do
    if [[ ! -f "$f" ]]; then
        echo "ERROR: required file not found: $f" >&2
        exit 1
    fi
done

smets=( "$SMET_DIR"/cluster_*.smet )
if [[ ${{#smets[@]}} -eq 0 ]]; then
    echo "ERROR: no cluster .smet files found in $SMET_DIR" >&2
    exit 1
fi

mkdir -p "$OUTPUT_DIR"

echo "=== {display_name} SNOWPACK run ==="
echo "    Start:    $BDATE"
echo "    End:      $EDATE"
echo "    Clusters: ${{#smets[@]}}"
[[ -n "$CLUSTERS_FILE" ]] && echo "    Filter:   $CLUSTERS_FILE"
echo "    Started:  $(date -u)"
echo ""

# Build cluster filter set (if provided)
declare -A CLUSTER_FILTER
if [[ -n "$CLUSTERS_FILE" && -f "$CLUSTERS_FILE" ]]; then
    if [[ "$CLUSTERS_FILE" == *.json ]]; then
        while IFS= read -r cid_num; do
            CLUSTER_FILTER["cluster_$(printf '%04d' "$cid_num")"]=1
        done < <(python3 -c "
import json, sys
with open('$CLUSTERS_FILE') as f:
    data = json.load(f)
for item in data:
    print(item['cid'])
")
    else
        while IFS= read -r line; do
            CLUSTER_FILTER["$line"]=1
        done < "$CLUSTERS_FILE"
    fi
    echo "    Filtered to ${{#CLUSTER_FILTER[@]}} clusters"
fi

for smet in "${{smets[@]}}"; do
    cid=$(basename "$smet" .smet)
    if [[ ${{#CLUSTER_FILTER[@]}} -gt 0 && -z "${{CLUSTER_FILTER[$cid]:-}}" ]]; then
        continue
    fi

    lat=$(awk -F'=' '/^latitude/{{gsub(/ /,"",$2); print $2}}' "$smet")
    lon=$(awk -F'=' '/^longitude/{{gsub(/ /,"",$2); print $2}}' "$smet")
    alt=$(awk -F'=' '/^altitude/{{gsub(/ /,"",$2); print $2}}' "$smet")

    res_sno="$OUTPUT_DIR/${{cid}}_${{cid}}.sno"
    cluster_sno="$SNOW_IN_DIR/${{cid}}.sno"
    if [[ -f "$res_sno" ]]; then
        cp "$res_sno" "$cluster_sno"
    else
        sed -e "s/WRFPT/$cid/g"  \\
            -e "s/WRFNAME/$cid/g" \\
            -e "s/WRFLAT/$lat/g"  \\
            -e "s/WRFLON/$lon/g"  \\
            -e "s/WRFELEV/$alt/g" \\
            -e "s/WRFDATE/${{BDATE%T*}}/g" \\
            "$TEMPLATE_SNO" > "$cluster_sno"
    fi

    cluster_ini="$OUTPUT_DIR/${{cid}}.ini"
    cat > "$cluster_ini" << EOF
IMPORT_BEFORE = $MASTER_CFG

[Input]
METEOPATH  = $SMET_DIR
SNOWPATH   = $SNOW_IN_DIR
METEOFILE1 = $cid
SNOWFILE1  = $cid

[Output]
METEOPATH  = $OUTPUT_DIR
SNOWPATH   = $OUTPUT_DIR
EXPERIMENT = $cid
EOF

    "$SNOWPACK_BIN" -c "$cluster_ini" -b "$BDATE" -e "$EDATE" \\
        > "$OUTPUT_DIR/${{cid}}.log" 2>&1 &

    ct=$(ps aux | grep "[s]nowpack.*exe" | wc -l)
    while [[ $ct -ge $MAX_JOBS ]]; do
        sleep 1
        ct=$(ps aux | grep "[s]nowpack.*exe" | wc -l)
    done
done

wait
echo "=== Run complete: $(date -u) ==="

n_ok=0; n_fail=0
for log in "$OUTPUT_DIR"/cluster_*.log; do
    if grep -q "done!" "$log" 2>/dev/null; then
        n_ok=$((n_ok + 1))
    else
        n_fail=$((n_fail + 1))
    fi
done
echo "    OK: $n_ok   Failed: $n_fail"
if [[ $n_fail -gt 0 ]]; then
    echo "    Failed clusters:"
    for log in "$OUTPUT_DIR"/cluster_*.log; do
        if ! grep -q "done!" "$log" 2>/dev/null; then
            echo "      $(basename "$log" .log)"
        fi
    done
fi

echo ""
echo "=== Aggregating results to Zarr ==="
$REPO_DIR/.venv/bin/python3 $REPO_DIR/src/avachain/build_zarr_chunked.py \\
    --pro-dir "$OUTPUT_DIR" --zarr-out "$OUTPUT_DIR/slope_snowpack.zarr"
echo "=== Zarr Build Complete ==="
"""

_RUN_OPERATIONAL_TEMPLATE = """\
#!/bin/bash
# run_{slope_name}.sh — Operational pipeline for {display_name}.
# Generated by install.py from slopes/{slope_name}/slope_config.toml
#
# Runs the incremental pipeline after a new UAS survey:
#   resample → gap_fill → cluster_update → smet → nwp_ingest → SNOWPACK → analyze → scenarios
#
# Usage:
#   ./run_{slope_name}.sh                                    # defaults
#   ./run_{slope_name}.sh --survey data/surveys/YYYYMMDD.tif
#   ./run_{slope_name}.sh --snapshot 2026-03-14
#   ./run_{slope_name}.sh --n-triggers 3
#   ./run_{slope_name}.sh --no-nwp                          # skip NWP forecast extension
#
#   # With avalanche reinitialization:
#   ./run_{slope_name}.sh --snapshot 2026-01-17 \\
#       --reinit --event-date 2026-01-18 \\
#       --date-before 2026-01-14 --date-after 2026-01-20
#
# Prerequisites:
#   - Full pipeline run at least once (cluster map exists)
#   - New survey .tif is in data/surveys/

set -euo pipefail

PROJECT_DIR={project_dir}
SLOPE_SCRIPTS=$PROJECT_DIR/slopes/{slope_name}
SLOPE_DIR=${{SLOPE_DIR:-{slope_dir}}}
TOML=$PROJECT_DIR/slopes/{slope_name}/slope_config.toml
PIPELINE="python $PROJECT_DIR/src/avachain/forcing_pipeline.py --toml $TOML"
ANALYSIS="python $PROJECT_DIR/src/avachain/analysis_pipeline.py --toml $TOML"
NWP="python $PROJECT_DIR/src/avachain/nwp_ingest.py --toml $TOML"
VENV=$PROJECT_DIR/.venv/bin/activate
LOG_DIR=$PROJECT_DIR/outputs/{slope_name}/logs

SURVEY_FILE=""
SNAPSHOT_DATE=""
N_TRIGGERS={n_triggers}
SIZE_FACTORS="{size_factors}"
DEPTH_PCTS="{depth_pcts}"
REINIT=0
EVENT_DATE=""
DATE_BEFORE=""
DATE_AFTER=""
REINIT_GEOJSON=""
NO_NWP=0
STABLE_TS=""

while [[ $# -gt 0 ]]; do
    case "$1" in
        --survey)          SURVEY_FILE="$2"; shift 2 ;;
        --snapshot)        SNAPSHOT_DATE="$2"; shift 2 ;;
        --n-triggers)      N_TRIGGERS="$2"; shift 2 ;;
        --size-factors)    SIZE_FACTORS="$2"; shift 2 ;;
        --depth-pcts)      DEPTH_PCTS="$2"; shift 2 ;;
        --reinit)          REINIT=1; shift ;;
        --event-date)      EVENT_DATE="$2"; shift 2 ;;
        --date-before)     DATE_BEFORE="$2"; shift 2 ;;
        --date-after)      DATE_AFTER="$2"; shift 2 ;;
        --reinit-geojson)  REINIT_GEOJSON="$2"; shift 2 ;;
        --no-nwp)          NO_NWP=1; shift ;;
        *)                 echo "Unknown arg: $1"; exit 1 ;;
    esac
done

if [[ $REINIT -eq 1 ]]; then
    if [[ -z "$EVENT_DATE" || -z "$DATE_BEFORE" || -z "$DATE_AFTER" ]]; then
        echo "ERROR: --reinit requires --event-date, --date-before, --date-after" >&2
        exit 1
    fi
fi

mkdir -p "$LOG_DIR"
TIMESTAMP=$(date +%Y%m%d_%H%M%S)
LOGFILE="$LOG_DIR/{slope_name}_${{TIMESTAMP}}.log"
exec > >(tee -a "$LOGFILE") 2>&1

echo "============================================================"
echo "  {display_name} — Operational Pipeline Update"
echo "  Started: $(date)"
echo "  Reinit:  $REINIT"
[[ $REINIT -eq 1 ]] && echo "  Event:   $EVENT_DATE ($DATE_BEFORE → $DATE_AFTER)"
echo "  Log:     $LOGFILE"
echo "============================================================"
echo ""

cd "$PROJECT_DIR"
source "$VENV"

# Save each cluster's _res.sno as its _anchor.sno in the output directory.
# Called after any SNOWPACK run that uses only observed/corrected forcing
# (survey run or reinit pass 2) — establishes the restart point for NWP cycles.
save_anchor_sno() {{
    local n=0
    for res_sno in "$SLOPE_DIR/output"/cluster_*_cluster_*.sno; do
        [[ -f "$res_sno" ]] || continue
        stem=$(basename "$res_sno")
        cid="${{stem%%_cluster_*.sno}}"
        cp "$res_sno" "$SLOPE_DIR/output/${{cid}}_anchor.sno"
        n=$((n + 1))
    done
    echo "    Saved anchor .sno for $n clusters"
}}

# Copy each cluster's _anchor.sno back to input/snow/ so the next SNOWPACK
# run starts from the last observation-grounded state rather than the
# forecast-contaminated _res.sno from a prior NWP cycle.
restore_anchor_sno() {{
    local n=0
    for anchor_sno in "$SLOPE_DIR/output"/cluster_*_anchor.sno; do
        [[ -f "$anchor_sno" ]] || continue
        stem=$(basename "$anchor_sno")
        cid="${{stem%_anchor.sno}}"
        cp "$anchor_sno" "$SLOPE_DIR/input/snow/${{cid}}.sno"
        n=$((n + 1))
    done
    echo "    Restored anchor .sno for $n clusters → input/snow/"
}}

for f in outputs/{slope_name}/analysis/cluster_map.npy outputs/{slope_name}/analysis/cluster_map.tif; do
    if [[ ! -f "$f" ]]; then
        echo "ERROR: $f not found. Run the full pipeline first." >&2
        exit 1
    fi
done

SECONDS=0
SNAPSHOT_ARG=""
[[ -n "$SNAPSHOT_DATE" ]] && SNAPSHOT_ARG="--snapshot-date $SNAPSHOT_DATE"

echo ">>> Step 1: Resample"
step1_start=$SECONDS
$PIPELINE resample
step1_elapsed=$((SECONDS - step1_start))
echo "    Done: $((step1_elapsed / 60))m $((step1_elapsed % 60))s"
echo ""

echo ">>> Step 2: Gap-fill"
step2_start=$SECONDS
$PIPELINE gap_fill
step2_elapsed=$((SECONDS - step2_start))
echo "    Done: $((step2_elapsed / 60))m $((step2_elapsed % 60))s"
echo ""

echo ">>> Step 2b: Cluster update"
step2b_start=$SECONDS
$PIPELINE cluster_update
step2b_elapsed=$((SECONDS - step2b_start))
echo "    Done: $((step2b_elapsed / 60))m $((step2b_elapsed % 60))s"
echo ""

echo ">>> Step 2c: SMET generation"
step2c_start=$SECONDS
$PIPELINE smet
step2c_elapsed=$((SECONDS - step2c_start))
echo "    Done: $((step2c_elapsed / 60))m $((step2c_elapsed % 60))s"
echo ""

echo ">>> Step 2d: NWP forecast extension"
step2d_start=$SECONDS
NWP_EDATE=""
if [[ $NO_NWP -eq 0 ]]; then
    $NWP --lead-hours 48 || echo "    WARNING: nwp_ingest failed — continuing without NWP extension"
    _ts_output=$(python3 -c "
import sys; sys.path.insert(0, '$PROJECT_DIR/src/avachain')
from nwp_ingest import get_stable_ts
from config import ProjectConfig
from pathlib import Path
import pandas as pd
cfg = ProjectConfig.from_toml(Path('$TOML'))
wrf = Path(cfg.wrf_smet_file)
if wrf.exists():
    ts = get_stable_ts(wrf)
    if ts:
        print(ts.strftime('%Y-%m-%dT%H:%M'),
              (ts + pd.Timedelta(hours=48)).strftime('%Y-%m-%dT%H:%M'))
" 2>/dev/null)
    if [[ -n "$_ts_output" ]]; then
        STABLE_TS=$(echo "$_ts_output" | cut -d' ' -f1)
        NWP_EDATE=$(echo "$_ts_output" | cut -d' ' -f2)
        echo "    T_stable  = $STABLE_TS"
        echo "    NWP EDATE = $NWP_EDATE (T_stable + 48h)"
    else
        echo "    WRF not available; SNOWPACK will use default season end"
    fi
else
    echo "    Skipped (--no-nwp)"
fi
step2d_elapsed=$((SECONDS - step2d_start))
echo "    Done: $((step2d_elapsed / 60))m $((step2d_elapsed % 60))s"
echo ""

echo ">>> Step 3: SNOWPACK simulation"
step3_start=$SECONDS

if [[ $REINIT -eq 1 ]]; then
    REINIT_SNAPSHOT="$SNAPSHOT_DATE"
    if [[ -z "$REINIT_SNAPSHOT" ]]; then
        REINIT_SNAPSHOT=$(python3 -c "from datetime import datetime, timedelta; \\
            print((datetime.strptime('$EVENT_DATE','%Y-%m-%d')-timedelta(1)).strftime('%Y-%m-%d'))")
    fi

    echo "    Restoring anchor .sno (survey-grounded state) for pass 1"
    restore_anchor_sno

    echo "    Pass 1: survey anchor → ${{EVENT_DATE}}T18:00"
    bash "$SLOPE_SCRIPTS/run_snowpack.sh" "" "${{EVENT_DATE}}T18:00"

    echo ""
    echo "    Analyzing snowpack at $REINIT_SNAPSHOT for slab thickness..."
    $ANALYSIS analyze --snapshot-date "$REINIT_SNAPSHOT"

    echo ""
    echo "    Reinit: scouring release clusters for $EVENT_DATE event"
    REINIT_CMD="$PIPELINE reinit --event-date $EVENT_DATE"
    REINIT_CMD="$REINIT_CMD --date-before $DATE_BEFORE --date-after $DATE_AFTER"
    REINIT_CMD="$REINIT_CMD --snapshot-date $REINIT_SNAPSHOT"
    [[ -n "$REINIT_GEOJSON" ]] && REINIT_CMD="$REINIT_CMD --release-geojson $REINIT_GEOJSON"
    $REINIT_CMD

    echo ""
    echo "    Pass 2: $EVENT_DATE → current date (scoured clusters only)"
    REINIT_STATS="$PROJECT_DIR/outputs/analysis/reinit_stats_${{EVENT_DATE}}.json"
    if [[ -f "$REINIT_STATS" ]]; then
        bash "$SLOPE_SCRIPTS/run_snowpack.sh" "" "" "$REINIT_STATS"
    else
        echo "    WARNING: reinit stats not found, rerunning all clusters"
        bash "$SLOPE_SCRIPTS/run_snowpack.sh"
    fi

    echo ""
    echo "    Saving anchor .sno (post-reinit observed state)"
    save_anchor_sno
else
    if [[ -n "$STABLE_TS" && $NO_NWP -eq 0 ]]; then
        echo "    Observed pass: → $STABLE_TS"
        bash "$SLOPE_SCRIPTS/run_snowpack.sh" "" "$STABLE_TS"
        echo ""
        echo "    Saving anchor .sno (observation-grounded state at T_stable)"
        save_anchor_sno
        echo ""
        echo "    Restoring anchor .sno for forecast pass"
        restore_anchor_sno
        echo "    Forecast pass: $STABLE_TS → $NWP_EDATE"
        bash "$SLOPE_SCRIPTS/run_snowpack.sh" "" "$NWP_EDATE"
    else
        echo "    Incremental from restart files"
        bash "$SLOPE_SCRIPTS/run_snowpack.sh"
        echo ""
        echo "    Saving anchor .sno"
        save_anchor_sno
    fi
fi

step3_elapsed=$((SECONDS - step3_start))
echo "    Done: $((step3_elapsed / 60))m $((step3_elapsed % 60))s"
echo ""

echo ">>> Step 4: Analysis + scenario generation"
step4_start=$SECONDS
$ANALYSIS analyze $SNAPSHOT_ARG
$ANALYSIS scenarios $SNAPSHOT_ARG \\
    --n-triggers "$N_TRIGGERS" \\
    --size-factors $SIZE_FACTORS \\
    --depth-pcts $DEPTH_PCTS
step4_elapsed=$((SECONDS - step4_start))
echo "    Done: $((step4_elapsed / 60))m $((step4_elapsed % 60))s"
echo ""

total_elapsed=$SECONDS
echo "============================================================"
echo "  {display_name} — Operational update complete"
echo "  Finished: $(date)"
echo "  Total:    $((total_elapsed / 3600))h $(((total_elapsed % 3600) / 60))m $((total_elapsed % 60))s"
echo ""
echo "  Step 1  (resample):        $((step1_elapsed / 60))m $((step1_elapsed % 60))s"
echo "  Step 2  (gap_fill):        $((step2_elapsed / 60))m $((step2_elapsed % 60))s"
echo "  Step 2b (cluster_update):  $((step2b_elapsed / 60))m $((step2b_elapsed % 60))s"
echo "  Step 2c (smet):            $((step2c_elapsed / 60))m $((step2c_elapsed % 60))s"
echo "  Step 2d (nwp_ingest):      $((step2d_elapsed / 60))m $((step2d_elapsed % 60))s"
echo "  Step 3  (SNOWPACK):        $((step3_elapsed / 60))m $((step3_elapsed % 60))s"
[[ $REINIT -eq 1 ]] && echo "    (three-pass: run → reinit → rerun + anchor save)"
echo "  Step 4  (analysis):        $((step4_elapsed / 60))m $((step4_elapsed % 60))s"
echo ""
echo "  Scenarios: $PROJECT_DIR/outputs/{slope_name}/scenarios/"
echo "  Log:       $LOGFILE"
echo "============================================================"
"""


# ---------------------------------------------------------------------------
# WRF discovery
# ---------------------------------------------------------------------------

def _find_season_dir(fcst_base: Path) -> Path | None:
    """Return the most recent year-only directory (e.g. '2025', not '2025-01-31')."""
    dirs = [d for d in fcst_base.iterdir()
            if d.is_dir() and re.fullmatch(r'\d{4}', d.name)]
    return max(dirs, key=lambda d: d.name) if dirs else None


def _read_smet_latlon(path: Path) -> tuple[float, float] | None:
    """Read latitude and longitude from a SMET file header. Returns None on error."""
    lat = lon = None
    try:
        with open(path) as f:
            for line in f:
                stripped = line.strip()
                if stripped == "[DATA]":
                    break
                if "=" in stripped and not stripped.startswith("["):
                    k, _, v = stripped.partition("=")
                    k = k.strip()
                    if k == "latitude":
                        lat = float(v.strip())
                    elif k == "longitude":
                        lon = float(v.strip())
                if lat is not None and lon is not None:
                    return lat, lon
    except Exception:
        return None
    return (lat, lon) if lat is not None and lon is not None else None


def _read_smet_slope_azi(path: Path) -> float | None:
    """Read slope_azi from a SMET file header."""
    try:
        with open(path) as f:
            for line in f:
                stripped = line.strip()
                if stripped == "[DATA]":
                    break
                if stripped.startswith("slope_azi"):
                    _, _, v = stripped.partition("=")
                    return float(v.strip())
    except Exception:
        return None
    return None


def _haversine_km(lat1: float, lon1: float, lat2: float, lon2: float) -> float:
    R = 6371.0
    dlat = math.radians(lat2 - lat1)
    dlon = math.radians(lon2 - lon1)
    a = (math.sin(dlat / 2) ** 2
         + math.cos(math.radians(lat1)) * math.cos(math.radians(lat2))
         * math.sin(dlon / 2) ** 2)
    return 2 * R * math.asin(math.sqrt(a))


def _aspect_diff(a1: float, a2: float) -> float:
    d = abs(a1 - a2) % 360
    return min(d, 360 - d)


def _find_best_wrf(cfg: dict) -> dict | None:
    """
    Scan WRF forecast directories and return the closest grid cell with the
    best aspect match to the slope.

    Each grid-cell directory contains:
      <grid_id>_res.smet          — flat field (slope_angle=0)
      <grid_id>1_res.smet …       — aspect variants (slope_azi 0/90/180/270)

    Returns a dict with: zone, grid_id, smet_dir, smet_file, lat, lon,
    slope_azi, dist_km.  Returns None if the fcst directory is unavailable.
    """
    wrf_cfg = cfg.get("wrf", {})
    fcst_base_str = wrf_cfg.get("fcst_base_dir", "")
    if not fcst_base_str:
        return None
    fcst_base = Path(fcst_base_str)
    if not fcst_base.exists():
        return None

    season_name = wrf_cfg.get("season", "")
    if season_name:
        season_dir = fcst_base / season_name
    else:
        season_dir = _find_season_dir(fcst_base)

    if not season_dir or not season_dir.exists():
        return None

    slope_lat  = float(cfg["slope"].get("latitude", 0))
    slope_lon  = float(cfg["slope"].get("longitude", 0))
    slope_asp  = float(cfg["slope"].get("aspect_deg", 0))

    print(f"  Scanning WRF zones in {season_dir} ...")

    best_dist    = float("inf")
    best_cell: dict | None = None

    for zone_dir in sorted(season_dir.glob("zone*")):
        for grid_dir in sorted(zone_dir.iterdir()):
            if not grid_dir.is_dir():
                continue
            flat_smet = grid_dir / f"{grid_dir.name}_res.smet"
            if not flat_smet.exists():
                smets = sorted(grid_dir.glob("*_res.smet"))
                if not smets:
                    continue
                flat_smet = smets[0]

            coords = _read_smet_latlon(flat_smet)
            if coords is None:
                continue
            lat, lon = coords
            dist = _haversine_km(slope_lat, slope_lon, lat, lon)
            if dist < best_dist:
                best_dist = dist
                best_cell = {
                    "zone": zone_dir.name,
                    "grid_id": grid_dir.name,
                    "grid_dir": grid_dir,
                    "lat": lat,
                    "lon": lon,
                    "dist_km": dist,
                }

    if best_cell is None:
        return None

    # Among aspect variants in the selected cell, pick the closest aspect match
    grid_dir = best_cell["grid_dir"]
    flat_name = f"{grid_dir.name}_res.smet"
    aspect_smets = sorted(f for f in grid_dir.glob("*_res.smet")
                          if f.name != flat_name)

    selected_smet = grid_dir / flat_name   # fallback to flat
    selected_azi  = 0.0

    if aspect_smets:
        best_diff = float("inf")
        for smet in aspect_smets:
            azi = _read_smet_slope_azi(smet)
            if azi is None:
                continue
            diff = _aspect_diff(slope_asp, azi)
            if diff < best_diff:
                best_diff    = diff
                selected_smet = smet
                selected_azi  = azi

    return {
        "zone":      best_cell["zone"],
        "grid_id":   best_cell["grid_id"],
        "smet_dir":  str(grid_dir),
        "smet_file": str(selected_smet),
        "lat":       best_cell["lat"],
        "lon":       best_cell["lon"],
        "dist_km":   best_cell["dist_km"],
        "slope_azi": selected_azi,
    }


def _update_wrf_in_toml(toml_path: Path, wrf: dict) -> None:
    """Write WRF selection results back into the [wrf] section of the TOML."""
    text = toml_path.read_text()
    # String fields — always written with quotes
    str_fields = {
        "wrf_smet_dir":  wrf["smet_dir"],
        "wrf_zone":      wrf["zone"],
        "wrf_grid_id":   wrf["grid_id"],
        "wrf_smet_file": wrf["smet_file"],
    }
    for key, value in str_fields.items():
        text = re.sub(
            rf'^({re.escape(key)}\s*=\s*)""',
            rf'\g<1>"{value}"',
            text,
            flags=re.MULTILINE,
        )
    # Float field — written without quotes
    dist_str = str(round(wrf["dist_km"], 3))
    text = re.sub(
        r'^(wrf_dist_km\s*=\s*)0\.0',
        rf'\g<1>{dist_str}',
        text,
        flags=re.MULTILINE,
    )
    toml_path.write_text(text)


# ---------------------------------------------------------------------------
# Directory creation
# ---------------------------------------------------------------------------

def _make_dirs(cfg: dict) -> None:
    project_dir = Path(cfg["paths"]["project_dir"])
    slope_name  = cfg["slope"]["name"]
    paths       = cfg["paths"]
    slope_dir   = project_dir / paths.get("slope_dir",   f"snowpack/{slope_name}")
    output_dir  = project_dir / paths.get("output_dir",  f"outputs/{slope_name}")

    # Input dirs — derived from TOML paths so each slope is self-contained
    file_keys = ("dem", "weather_csv", "boundary_kml", "start_zone_kml", "release_geojson")
    dir_keys  = ("survey_dir",)
    dirs: list[Path] = []
    for k in file_keys:
        if v := paths.get(k):
            dirs.append((project_dir / v).parent)
    for k in dir_keys:
        if v := paths.get(k):
            dirs.append(project_dir / v)

    # Slope runtime dirs
    dirs += [
        slope_dir / "input" / "snow",
        slope_dir / "input" / "smet",
        slope_dir / "output",
    ]

    # Per-slope output dirs
    for sub in ("analysis", "scenarios", "plots", "models", "hourly_grids",
                "resampled_1m", "logs"):
        dirs.append(output_dir / sub)

    # Shared dirs (not namespaced — used by all slopes)
    dirs += [
        project_dir / "outputs" / "weather",
        project_dir / "slopes" / slope_name / "config",
        project_dir / "slopes" / slope_name / "external_models",
    ]

    # Deduplicate while preserving order
    seen: set[Path] = set()
    unique: list[Path] = []
    for d in dirs:
        if d not in seen:
            seen.add(d)
            unique.append(d)

    created = [d for d in unique if not d.exists()]
    for d in created:
        d.mkdir(parents=True, exist_ok=True)
    if created:
        print(f"  Created {len(created)} director(ies):")
        for d in created:
            print(f"    {d.relative_to(project_dir)}")
    else:
        print("  All directories already exist.")


# ---------------------------------------------------------------------------
# Script / config generation
# ---------------------------------------------------------------------------

def _write_script(path: Path, content: str) -> None:
    path.write_text(content)
    path.chmod(path.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP)


def _render_master_ini(cfg: dict) -> str:
    slope = cfg["slope"]
    return _MASTER_INI_TEMPLATE.format(
        display_name=slope.get("display_name", slope["name"]),
        slope_name=slope["name"],
    )


def _render_run_snowpack(cfg: dict) -> str:
    paths      = cfg["paths"]
    slope      = cfg["slope"]
    sp         = cfg.get("snowpack", {})
    project_dir = paths["project_dir"]
    slope_name  = slope["name"]
    slope_dir   = str(Path(project_dir) / paths.get("slope_dir", f"snowpack/{slope_name}"))
    return _RUN_SNOWPACK_TEMPLATE.format(
        display_name  = slope.get("display_name", slope_name),
        slope_name    = slope_name,
        project_dir   = project_dir,
        slope_dir     = slope_dir,
        snowpack_bin  = sp.get("binary", "/path/to/snowpack"),
        snowpack_lib  = sp.get("lib_dir", ""),
        season_end    = sp.get("season_end", "YYYY-MM-DD"),
        max_jobs      = sp.get("max_parallel_jobs", 30),
    )


def _render_run_operational(cfg: dict) -> str:
    paths       = cfg["paths"]
    slope       = cfg["slope"]
    sc          = cfg.get("scenarios", {})
    project_dir = paths["project_dir"]
    slope_name  = slope["name"]
    slope_dir   = str(Path(project_dir) / paths.get("slope_dir", f"snowpack/{slope_name}"))
    size_factors = sc.get("size_factors", [0.70, 0.85, 1.00, 1.15, 1.30])
    depth_pcts   = sc.get("depth_percentiles", [10, 50, 90])
    return _RUN_OPERATIONAL_TEMPLATE.format(
        display_name  = slope.get("display_name", slope_name),
        slope_name    = slope_name,
        project_dir   = project_dir,
        slope_dir     = slope_dir,
        n_triggers    = sc.get("n_triggers", 5),
        size_factors  = " ".join(str(x) for x in size_factors),
        depth_pcts    = " ".join(str(x) for x in depth_pcts),
    )


# ---------------------------------------------------------------------------
# Validation
# ---------------------------------------------------------------------------

def _validate(cfg: dict) -> list[str]:
    warnings = []
    sp = cfg.get("snowpack", {})
    if sp.get("binary") and not Path(sp["binary"]).exists():
        warnings.append(f"SNOWPACK binary not found: {sp['binary']}")
    if sp.get("season_end", "YYYY-MM-DD") == "YYYY-MM-DD":
        warnings.append("snowpack.season_end is not set — edit the TOML before running SNOWPACK")
    stations = {s["role"]: s for s in cfg.get("stations", [])}
    for role in ("summit", "base"):
        if role not in stations:
            warnings.append(f"No [[stations]] entry with role = \"{role}\"")
        elif not stations[role].get("sql_id"):
            warnings.append(f"stations[{role}].sql_id is empty")
    if cfg["paths"].get("project_dir") in ("/path/to/snowpack_model_feeder", "/path/to/avachain", ""):
        warnings.append("paths.project_dir still has the template placeholder value")
    output_dir = cfg["paths"].get("output_dir", "")
    if output_dir in ("outputs", ""):
        slope_name = cfg["slope"]["name"]
        warnings.append(
            f"paths.output_dir = 'outputs' — use 'outputs/{slope_name}' "
            f"so each slope's outputs stay separate"
        )
    return warnings


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _load_toml(path: Path) -> dict:
    with open(path, "rb") as f:
        return tomllib.load(f)


def _find_toml(repo_root: Path, slope_name: str) -> Path:
    return repo_root / "slopes" / slope_name / "slope_config.toml"


def _list_slopes(repo_root: Path) -> None:
    tomls = sorted((repo_root / "slopes").glob("*/slope_config.toml"))
    if not tomls:
        print("No slope_config.toml files found under slopes/")
        return
    print(f"{'Slope name':<20}  {'Display name':<30}  Config")
    print("-" * 80)
    for p in tomls:
        try:
            data = _load_toml(p)
            name    = data.get("slope", {}).get("name", "?")
            display = data.get("slope", {}).get("display_name", "?")
            print(f"{name:<20}  {display:<30}  {p}")
        except Exception as e:
            print(f"{'(error)':<20}  {str(e):<30}  {p}")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Bootstrap a new slope for the avachain pipeline.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python install.py slopes/little_prof/slope_config.toml
  python install.py --slope little_prof
  python install.py --list
""",
    )
    parser.add_argument("toml", nargs="?", help="Path to slope_config.toml")
    parser.add_argument("--slope", metavar="NAME",
                        help="Slope name; resolves to slopes/<name>/slope_config.toml")
    parser.add_argument("--list", action="store_true",
                        help="List all configured slopes and exit")
    parser.add_argument("--skip-wrf", action="store_true",
                        help="Skip WRF zone discovery (useful when /ssd is not mounted)")
    args = parser.parse_args()

    repo_root = Path(__file__).parent

    if args.list:
        _list_slopes(repo_root)
        return

    if args.toml:
        toml_path = Path(args.toml)
    elif args.slope:
        toml_path = _find_toml(repo_root, args.slope)
    else:
        parser.error("Provide a TOML path or --slope <name>")

    if not toml_path.exists():
        sys.exit(f"ERROR: config not found: {toml_path}")

    cfg          = _load_toml(toml_path)
    slope_name   = cfg["slope"]["name"]
    display_name = cfg["slope"].get("display_name", slope_name)
    project_dir  = Path(cfg["paths"]["project_dir"])

    print(f"\n=== Installing slope: {display_name} ({slope_name}) ===\n")

    warnings = _validate(cfg)
    if warnings:
        print("  Warnings:")
        for w in warnings:
            print(f"    ⚠  {w}")
        print()

    # --- Directories ---
    print("Creating directory structure...")
    _make_dirs(cfg)
    print()

    # --- WRF zone discovery ---
    if not args.skip_wrf:
        print("Finding closest WRF grid cell...")
        wrf = _find_best_wrf(cfg)
        if wrf:
            print(f"  Selected: {wrf['zone']}/{wrf['grid_id']}")
            print(f"  Distance: {wrf['dist_km']:.1f} km")
            print(f"  Aspect variant: slope_azi={wrf['slope_azi']:.0f}°  "
                  f"(slope aspect={cfg['slope'].get('aspect_deg', '?')}°)")
            print(f"  File: {wrf['smet_file']}")
            _update_wrf_in_toml(toml_path, wrf)
            print(f"  → Written to {toml_path.name}")
        else:
            print("  WRF directory not accessible — skipping. "
                  "Rerun without --skip-wrf when /ssd is mounted.")
        print()
    else:
        print("Skipping WRF discovery (--skip-wrf).\n")

    # --- master_config.ini ---
    ini_path = project_dir / "slopes" / slope_name / "config" / "master_config.ini"
    # Don't overwrite an existing customised ini
    if ini_path.exists():
        print(f"Skipping master_config.ini (already exists at {ini_path})")
    else:
        ini_path.write_text(_render_master_ini(cfg))
        print(f"Wrote {ini_path.relative_to(project_dir)}")
    print()

    # --- run_snowpack.sh ---
    snowpack_script = project_dir / "slopes" / slope_name / "run_snowpack.sh"
    print(f"Writing {snowpack_script.relative_to(project_dir)} ...")
    _write_script(snowpack_script, _render_run_snowpack(cfg))

    # --- run_<slope>.sh ---
    operational_script = project_dir / f"run_{slope_name}.sh"
    print(f"Writing {operational_script.name} ...")
    _write_script(operational_script, _render_run_operational(cfg))

    # --- Cron ---
    hour_utc  = cfg.get("cron", {}).get("hour_utc", 20)
    log_path  = project_dir / "outputs" / "logs" / f"cron_{slope_name}.log"

    print()
    print("=" * 60)
    print("Installation complete.")
    print()
    print("Next steps:")
    print(f"  1. Drop DEM          → {cfg['paths'].get('dem', f'data/{slope_name}/dem/')}")
    print(f"  2. Drop first survey → {cfg['paths'].get('survey_dir', f'data/{slope_name}/surveys/')}/")
    print(f"  3. Drop template.sno → "
          f"{cfg['paths'].get('slope_dir', f'snowpack/{slope_name}')}/input/snow/")
    print()
    # If this looks like an existing installation being re-run with a newly
    # namespaced output_dir, print the one-time migration commands.
    out_dir = cfg["paths"].get("output_dir", "")
    if out_dir and out_dir != "outputs":
        flat_out = project_dir / "outputs"
        if (flat_out / "analysis").exists() and not (project_dir / out_dir / "analysis").exists():
            print("  *** One-time migration needed — move existing outputs into the")
            print(f"  *** new per-slope directory ({out_dir}):")
            print()
            print(f"    mkdir -p {project_dir}/{out_dir}")
            print(f"    for d in analysis scenarios plots models hourly_grids resampled_1m logs; do")
            print(f"      [ -d {flat_out}/$d ] && mv {flat_out}/$d {project_dir}/{out_dir}/$d")
            print(f"    done")
            print(f"    # outputs/weather stays in place (shared across slopes)")
            print()
    print()
    print("To schedule the daily run, add this line to your crontab")
    print("(run: crontab -e):")
    print()
    print(f"  0 {hour_utc} * * * {operational_script} >> {log_path} 2>&1")
    print()
    print("Generated files:")
    print(f"  {ini_path}")
    print(f"  {snowpack_script}")
    print(f"  {operational_script}")
    print("=" * 60)


if __name__ == "__main__":
    main()
