#!/bin/bash
# run_little_prof.sh — Operational pipeline for Little Professor.
# Generated by install.py from slopes/little_prof/slope_config.toml
#
# Runs the incremental pipeline after a new UAS survey:
#   resample → gap_fill → cluster_update → smet → SNOWPACK → analyze → scenarios
#
# Usage:
#   ./run_little_prof.sh                                    # defaults
#   ./run_little_prof.sh --survey data/surveys/YYYYMMDD.tif
#   ./run_little_prof.sh --snapshot 2026-03-14
#   ./run_little_prof.sh --n-triggers 3
#
#   # With avalanche reinitialization:
#   ./run_little_prof.sh --snapshot 2026-01-17 \
#       --reinit --event-date 2026-01-18 \
#       --date-before 2026-01-14 --date-after 2026-01-20
#
# Prerequisites:
#   - Full pipeline run at least once (cluster map exists)
#   - New survey .tif is in data/surveys/

set -euo pipefail

PROJECT_DIR=/home/ron/snowpack_model_feeder
SLOPE_SCRIPTS=$PROJECT_DIR/slopes/little_prof
SLOPE_DIR=${SLOPE_DIR:-/home/ron/snowpack_model_feeder/snowpack/little_prof}
PIPELINE="python $PROJECT_DIR/src/avachain/forcing_pipeline.py --project-dir $PROJECT_DIR"
ANALYSIS="python $PROJECT_DIR/src/avachain/analysis_pipeline.py --project-dir $PROJECT_DIR"
VENV=$PROJECT_DIR/.venv/bin/activate
LOG_DIR=$PROJECT_DIR/outputs/logs

SURVEY_FILE=""
SNAPSHOT_DATE=""
N_TRIGGERS=5
SIZE_FACTORS="0.7 0.85 1.0 1.15 1.3"
DEPTH_PCTS="10 50 90"
REINIT=0
EVENT_DATE=""
DATE_BEFORE=""
DATE_AFTER=""
REINIT_GEOJSON=""

while [[ $# -gt 0 ]]; do
    case "$1" in
        --survey)          SURVEY_FILE="$2"; shift 2 ;;
        --snapshot)        SNAPSHOT_DATE="$2"; shift 2 ;;
        --n-triggers)      N_TRIGGERS="$2"; shift 2 ;;
        --size-factors)    SIZE_FACTORS="$2"; shift 2 ;;
        --depth-pcts)      DEPTH_PCTS="$2"; shift 2 ;;
        --reinit)          REINIT=1; shift ;;
        --event-date)      EVENT_DATE="$2"; shift 2 ;;
        --date-before)     DATE_BEFORE="$2"; shift 2 ;;
        --date-after)      DATE_AFTER="$2"; shift 2 ;;
        --reinit-geojson)  REINIT_GEOJSON="$2"; shift 2 ;;
        *)                 echo "Unknown arg: $1"; exit 1 ;;
    esac
done

if [[ $REINIT -eq 1 ]]; then
    if [[ -z "$EVENT_DATE" || -z "$DATE_BEFORE" || -z "$DATE_AFTER" ]]; then
        echo "ERROR: --reinit requires --event-date, --date-before, --date-after" >&2
        exit 1
    fi
fi

mkdir -p "$LOG_DIR"
TIMESTAMP=$(date +%Y%m%d_%H%M%S)
LOGFILE="$LOG_DIR/little_prof_${TIMESTAMP}.log"
exec > >(tee -a "$LOGFILE") 2>&1

echo "============================================================"
echo "  Little Professor — Operational Pipeline Update"
echo "  Started: $(date)"
echo "  Reinit:  $REINIT"
[[ $REINIT -eq 1 ]] && echo "  Event:   $EVENT_DATE ($DATE_BEFORE → $DATE_AFTER)"
echo "  Log:     $LOGFILE"
echo "============================================================"
echo ""

cd "$PROJECT_DIR"
source "$VENV"

for f in outputs/analysis/cluster_map.npy outputs/analysis/cluster_map.tif; do
    if [[ ! -f "$f" ]]; then
        echo "ERROR: $f not found. Run the full pipeline first." >&2
        exit 1
    fi
done

SECONDS=0
SNAPSHOT_ARG=""
[[ -n "$SNAPSHOT_DATE" ]] && SNAPSHOT_ARG="--snapshot-date $SNAPSHOT_DATE"

echo ">>> Step 1: Resample"
step1_start=$SECONDS
$PIPELINE resample
step1_elapsed=$((SECONDS - step1_start))
echo "    Done: $((step1_elapsed / 60))m $((step1_elapsed % 60))s"
echo ""

echo ">>> Step 2: Gap-fill"
step2_start=$SECONDS
$PIPELINE gap_fill
step2_elapsed=$((SECONDS - step2_start))
echo "    Done: $((step2_elapsed / 60))m $((step2_elapsed % 60))s"
echo ""

echo ">>> Step 2b: Cluster update"
step2b_start=$SECONDS
$PIPELINE cluster_update
step2b_elapsed=$((SECONDS - step2b_start))
echo "    Done: $((step2b_elapsed / 60))m $((step2b_elapsed % 60))s"
echo ""

echo ">>> Step 2c: SMET generation"
step2c_start=$SECONDS
$PIPELINE smet
step2c_elapsed=$((SECONDS - step2c_start))
echo "    Done: $((step2c_elapsed / 60))m $((step2c_elapsed % 60))s"
echo ""

echo ">>> Step 3: SNOWPACK simulation"
step3_start=$SECONDS

if [[ $REINIT -eq 1 ]]; then
    REINIT_SNAPSHOT="$SNAPSHOT_DATE"
    if [[ -z "$REINIT_SNAPSHOT" ]]; then
        REINIT_SNAPSHOT=$(python3 -c "from datetime import datetime, timedelta; \
            print((datetime.strptime('$EVENT_DATE','%Y-%m-%d')-timedelta(1)).strftime('%Y-%m-%d'))")
    fi

    echo "    Pass 1: incremental → ${EVENT_DATE}T18:00"
    bash "$SLOPE_SCRIPTS/run_snowpack.sh" "" "${EVENT_DATE}T18:00"

    echo ""
    echo "    Analyzing snowpack at $REINIT_SNAPSHOT for slab thickness..."
    $ANALYSIS analyze --snapshot-date "$REINIT_SNAPSHOT"

    echo ""
    echo "    Reinit: scouring release clusters for $EVENT_DATE event"
    REINIT_CMD="$PIPELINE reinit --event-date $EVENT_DATE"
    REINIT_CMD="$REINIT_CMD --date-before $DATE_BEFORE --date-after $DATE_AFTER"
    REINIT_CMD="$REINIT_CMD --snapshot-date $REINIT_SNAPSHOT"
    [[ -n "$REINIT_GEOJSON" ]] && REINIT_CMD="$REINIT_CMD --release-geojson $REINIT_GEOJSON"
    $REINIT_CMD

    echo ""
    echo "    Pass 2: $EVENT_DATE → end of season (scoured clusters only)"
    REINIT_STATS="$PROJECT_DIR/outputs/analysis/reinit_stats_${EVENT_DATE}.json"
    if [[ -f "$REINIT_STATS" ]]; then
        bash "$SLOPE_SCRIPTS/run_snowpack.sh" "" "" "$REINIT_STATS"
    else
        echo "    WARNING: reinit stats not found, rerunning all clusters"
        bash "$SLOPE_SCRIPTS/run_snowpack.sh"
    fi
else
    echo "    Incremental from restart files"
    bash "$SLOPE_SCRIPTS/run_snowpack.sh"
fi

step3_elapsed=$((SECONDS - step3_start))
echo "    Done: $((step3_elapsed / 60))m $((step3_elapsed % 60))s"
echo ""

echo ">>> Step 4: Analysis + scenario generation"
step4_start=$SECONDS
$ANALYSIS analyze $SNAPSHOT_ARG
$ANALYSIS scenarios $SNAPSHOT_ARG \
    --n-triggers "$N_TRIGGERS" \
    --size-factors $SIZE_FACTORS \
    --depth-pcts $DEPTH_PCTS
step4_elapsed=$((SECONDS - step4_start))
echo "    Done: $((step4_elapsed / 60))m $((step4_elapsed % 60))s"
echo ""

total_elapsed=$SECONDS
echo "============================================================"
echo "  Little Professor — Operational update complete"
echo "  Finished: $(date)"
echo "  Total:    $((total_elapsed / 3600))h $(((total_elapsed % 3600) / 60))m $((total_elapsed % 60))s"
echo ""
echo "  Step 1  (resample):        $((step1_elapsed / 60))m $((step1_elapsed % 60))s"
echo "  Step 2  (gap_fill):        $((step2_elapsed / 60))m $((step2_elapsed % 60))s"
echo "  Step 2b (cluster_update):  $((step2b_elapsed / 60))m $((step2b_elapsed % 60))s"
echo "  Step 2c (smet):            $((step2c_elapsed / 60))m $((step2c_elapsed % 60))s"
echo "  Step 3  (SNOWPACK):        $((step3_elapsed / 60))m $((step3_elapsed % 60))s"
[[ $REINIT -eq 1 ]] && echo "    (two-pass: run → reinit → rerun)"
echo "  Step 4  (analysis):        $((step4_elapsed / 60))m $((step4_elapsed % 60))s"
echo ""
echo "  Scenarios: $PROJECT_DIR/outputs/scenarios/"
echo "  Log:       $LOGFILE"
echo "============================================================"
