#!/bin/bash
# run_little_prof.sh — Operational pipeline for Little Professor.
# Generated by install.py from slopes/little_prof/slope_config.toml
#
# Runs the incremental pipeline after a new UAS survey:
#   resample → gap_fill → cluster_update → smet → nwp_ingest → SNOWPACK → analyze → scenarios
#
# Usage:
#   ./run_little_prof.sh                                    # defaults
#   ./run_little_prof.sh --survey data/surveys/YYYYMMDD.tif
#   ./run_little_prof.sh --snapshot 2026-03-14
#   ./run_little_prof.sh --n-triggers 3
#   ./run_little_prof.sh --no-nwp                          # skip NWP forecast extension
#
#   # With avalanche reinitialization:
#   ./run_little_prof.sh --snapshot 2026-01-17 \
#       --reinit --event-date 2026-01-18 \
#       --date-before 2026-01-14 --date-after 2026-01-20
#
# Prerequisites:
#   - Full pipeline run at least once (cluster map exists)
#   - New survey .tif is in data/surveys/

set -euo pipefail

PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SLOPE_SCRIPTS=$PROJECT_DIR/slopes/little_prof
SLOPE_DIR=${SLOPE_DIR:-$PROJECT_DIR/snowpack/little_prof}
TOML=$PROJECT_DIR/slopes/little_prof/slope_config.toml
PIPELINE="python $PROJECT_DIR/src/avachain/forcing_pipeline.py --toml $TOML"
ANALYSIS="python $PROJECT_DIR/src/avachain/analysis_pipeline.py --toml $TOML"
NWP="python $PROJECT_DIR/src/avachain/nwp_ingest.py --toml $TOML"
VENV=$PROJECT_DIR/.venv/bin/activate
LOG_DIR=$PROJECT_DIR/outputs/little_prof/logs

SURVEY_FILE=""
SNAPSHOT_DATE=""
N_TRIGGERS=5
SIZE_FACTORS="0.7 0.85 1.0 1.15 1.3"
DEPTH_PCTS="10 50 90"
REINIT=0
EVENT_DATE=""
DATE_BEFORE=""
DATE_AFTER=""
REINIT_GEOJSON=""
NO_NWP=0
STABLE_TS=""

while [[ $# -gt 0 ]]; do
    case "$1" in
        --survey)          SURVEY_FILE="$2"; shift 2 ;;
        --snapshot)        SNAPSHOT_DATE="$2"; shift 2 ;;
        --n-triggers)      N_TRIGGERS="$2"; shift 2 ;;
        --size-factors)    SIZE_FACTORS="$2"; shift 2 ;;
        --depth-pcts)      DEPTH_PCTS="$2"; shift 2 ;;
        --reinit)          REINIT=1; shift ;;
        --event-date)      EVENT_DATE="$2"; shift 2 ;;
        --date-before)     DATE_BEFORE="$2"; shift 2 ;;
        --date-after)      DATE_AFTER="$2"; shift 2 ;;
        --reinit-geojson)  REINIT_GEOJSON="$2"; shift 2 ;;
        --no-nwp)          NO_NWP=1; shift ;;
        *)                 echo "Unknown arg: $1"; exit 1 ;;
    esac
done

if [[ $REINIT -eq 1 ]]; then
    if [[ -z "$EVENT_DATE" || -z "$DATE_BEFORE" || -z "$DATE_AFTER" ]]; then
        echo "ERROR: --reinit requires --event-date, --date-before, --date-after" >&2
        exit 1
    fi
fi

mkdir -p "$LOG_DIR"
TIMESTAMP=$(date +%Y%m%d_%H%M%S)
LOGFILE="$LOG_DIR/little_prof_${TIMESTAMP}.log"
exec > >(tee -a "$LOGFILE") 2>&1

echo "============================================================"
echo "  Little Professor — Operational Pipeline Update"
echo "  Started: $(date)"
echo "  Reinit:  $REINIT"
[[ $REINIT -eq 1 ]] && echo "  Event:   $EVENT_DATE ($DATE_BEFORE → $DATE_AFTER)"
echo "  Log:     $LOGFILE"
echo "============================================================"
echo ""

cd "$PROJECT_DIR"
source "$VENV"

# Save each cluster's _res.sno as its _anchor.sno in the output directory.
# Called after any SNOWPACK run that uses only observed/corrected forcing
# (survey run or reinit pass 2) — establishes the restart point for NWP cycles.
save_anchor_sno() {
    local n=0
    for res_sno in "$SLOPE_DIR/output"/cluster_*_cluster_*.sno; do
        [[ -f "$res_sno" ]] || continue
        stem=$(basename "$res_sno")
        cid="${stem%%_cluster_*.sno}"
        cp "$res_sno" "$SLOPE_DIR/output/${cid}_anchor.sno"
        n=$((n + 1))
    done
    echo "    Saved anchor .sno for $n clusters"
}

# Copy each cluster's _anchor.sno back to input/snow/ so the next SNOWPACK
# run starts from the last observation-grounded state rather than the
# forecast-contaminated _res.sno from a prior NWP cycle.
restore_anchor_sno() {
    local n=0
    for anchor_sno in "$SLOPE_DIR/output"/cluster_*_anchor.sno; do
        [[ -f "$anchor_sno" ]] || continue
        stem=$(basename "$anchor_sno")
        cid="${stem%_anchor.sno}"
        cp "$anchor_sno" "$SLOPE_DIR/input/snow/${cid}.sno"
        n=$((n + 1))
    done
    echo "    Restored anchor .sno for $n clusters → input/snow/"
}

for f in outputs/little_prof/analysis/cluster_map.npy outputs/little_prof/analysis/cluster_map.tif; do
    if [[ ! -f "$f" ]]; then
        echo "ERROR: $f not found. Run the full pipeline first." >&2
        exit 1
    fi
done

SECONDS=0
SNAPSHOT_ARG=""
[[ -n "$SNAPSHOT_DATE" ]] && SNAPSHOT_ARG="--snapshot-date $SNAPSHOT_DATE"

echo ">>> Step 1: Resample"
step1_start=$SECONDS
$PIPELINE resample
step1_elapsed=$((SECONDS - step1_start))
echo "    Done: $((step1_elapsed / 60))m $((step1_elapsed % 60))s"
echo ""

echo ">>> Step 2: Gap-fill"
step2_start=$SECONDS
$PIPELINE gap_fill
step2_elapsed=$((SECONDS - step2_start))
echo "    Done: $((step2_elapsed / 60))m $((step2_elapsed % 60))s"
echo ""

echo ">>> Step 2b: Cluster update"
step2b_start=$SECONDS
$PIPELINE cluster_update
step2b_elapsed=$((SECONDS - step2b_start))
echo "    Done: $((step2b_elapsed / 60))m $((step2b_elapsed % 60))s"
echo ""

echo ">>> Step 2c: SMET generation"
step2c_start=$SECONDS
$PIPELINE smet
step2c_elapsed=$((SECONDS - step2c_start))
echo "    Done: $((step2c_elapsed / 60))m $((step2c_elapsed % 60))s"
echo ""

echo ">>> Step 2d: NWP forecast extension"
step2d_start=$SECONDS
NWP_EDATE=""
if [[ $NO_NWP -eq 0 ]]; then
    $NWP --lead-hours 48 || echo "    WARNING: nwp_ingest failed — continuing without NWP extension"
    _ts_output=$(python3 -c "
import sys; sys.path.insert(0, '$PROJECT_DIR/src/avachain')
from nwp_ingest import get_stable_ts
from config import ProjectConfig
from pathlib import Path
import pandas as pd
cfg = ProjectConfig.from_toml(Path('$TOML'))
wrf = Path(cfg.wrf_smet_file)
if wrf.exists():
    ts = get_stable_ts(wrf)
    if ts:
        print(ts.strftime('%Y-%m-%dT%H:%M'),
              (ts + pd.Timedelta(hours=48)).strftime('%Y-%m-%dT%H:%M'))
" 2>/dev/null)
    if [[ -n "$_ts_output" ]]; then
        STABLE_TS=$(echo "$_ts_output" | cut -d' ' -f1)
        NWP_EDATE=$(echo "$_ts_output" | cut -d' ' -f2)
        echo "    T_stable  = $STABLE_TS"
        echo "    NWP EDATE = $NWP_EDATE (T_stable + 48h)"
    else
        echo "    WRF not available; SNOWPACK will use default season end"
    fi
else
    echo "    Skipped (--no-nwp)"
fi
step2d_elapsed=$((SECONDS - step2d_start))
echo "    Done: $((step2d_elapsed / 60))m $((step2d_elapsed % 60))s"
echo ""

echo ">>> Step 3: SNOWPACK simulation"
step3_start=$SECONDS

if [[ $REINIT -eq 1 ]]; then
    REINIT_SNAPSHOT="$SNAPSHOT_DATE"
    if [[ -z "$REINIT_SNAPSHOT" ]]; then
        REINIT_SNAPSHOT=$(python3 -c "from datetime import datetime, timedelta; \
            print((datetime.strptime('$EVENT_DATE','%Y-%m-%d')-timedelta(1)).strftime('%Y-%m-%d'))")
    fi

    echo "    Restoring anchor .sno (survey-grounded state) for pass 1"
    restore_anchor_sno

    echo "    Pass 1: survey anchor → ${EVENT_DATE}T18:00"
    bash "$SLOPE_SCRIPTS/run_snowpack.sh" "" "${EVENT_DATE}T18:00"

    echo ""
    echo "    Analyzing snowpack at $REINIT_SNAPSHOT for slab thickness..."
    $ANALYSIS analyze --snapshot-date "$REINIT_SNAPSHOT"

    echo ""
    echo "    Reinit: scouring release clusters for $EVENT_DATE event"
    REINIT_CMD="$PIPELINE reinit --event-date $EVENT_DATE"
    REINIT_CMD="$REINIT_CMD --date-before $DATE_BEFORE --date-after $DATE_AFTER"
    REINIT_CMD="$REINIT_CMD --snapshot-date $REINIT_SNAPSHOT"
    [[ -n "$REINIT_GEOJSON" ]] && REINIT_CMD="$REINIT_CMD --release-geojson $REINIT_GEOJSON"
    $REINIT_CMD

    echo ""
    echo "    Pass 2: $EVENT_DATE → current date (scoured clusters only)"
    REINIT_STATS="$PROJECT_DIR/outputs/analysis/reinit_stats_${EVENT_DATE}.json"
    if [[ -f "$REINIT_STATS" ]]; then
        bash "$SLOPE_SCRIPTS/run_snowpack.sh" "" "" "$REINIT_STATS"
    else
        echo "    WARNING: reinit stats not found, rerunning all clusters"
        bash "$SLOPE_SCRIPTS/run_snowpack.sh"
    fi

    echo ""
    echo "    Saving anchor .sno (post-reinit observed state)"
    save_anchor_sno
else
    if [[ -n "$STABLE_TS" && $NO_NWP -eq 0 ]]; then
        echo "    Observed pass: → $STABLE_TS"
        bash "$SLOPE_SCRIPTS/run_snowpack.sh" "" "$STABLE_TS"
        echo ""
        echo "    Saving anchor .sno (observation-grounded state at T_stable)"
        save_anchor_sno
        echo ""
        echo "    Restoring anchor .sno for forecast pass"
        restore_anchor_sno
        echo "    Forecast pass: $STABLE_TS → $NWP_EDATE"
        bash "$SLOPE_SCRIPTS/run_snowpack.sh" "" "$NWP_EDATE"
    else
        echo "    Incremental from restart files"
        bash "$SLOPE_SCRIPTS/run_snowpack.sh"
        echo ""
        echo "    Saving anchor .sno"
        save_anchor_sno
    fi
fi

step3_elapsed=$((SECONDS - step3_start))
echo "    Done: $((step3_elapsed / 60))m $((step3_elapsed % 60))s"
echo ""

echo ">>> Step 4: Analysis + scenario generation"
step4_start=$SECONDS
$ANALYSIS analyze $SNAPSHOT_ARG
$ANALYSIS scenarios $SNAPSHOT_ARG \
    --n-triggers "$N_TRIGGERS" \
    --size-factors $SIZE_FACTORS \
    --depth-pcts $DEPTH_PCTS
step4_elapsed=$((SECONDS - step4_start))
echo "    Done: $((step4_elapsed / 60))m $((step4_elapsed % 60))s"
echo ""

total_elapsed=$SECONDS
echo "============================================================"
echo "  Little Professor — Operational update complete"
echo "  Finished: $(date)"
echo "  Total:    $((total_elapsed / 3600))h $(((total_elapsed % 3600) / 60))m $((total_elapsed % 60))s"
echo ""
echo "  Step 1  (resample):        $((step1_elapsed / 60))m $((step1_elapsed % 60))s"
echo "  Step 2  (gap_fill):        $((step2_elapsed / 60))m $((step2_elapsed % 60))s"
echo "  Step 2b (cluster_update):  $((step2b_elapsed / 60))m $((step2b_elapsed % 60))s"
echo "  Step 2c (smet):            $((step2c_elapsed / 60))m $((step2c_elapsed % 60))s"
echo "  Step 2d (nwp_ingest):      $((step2d_elapsed / 60))m $((step2d_elapsed % 60))s"
echo "  Step 3  (SNOWPACK):        $((step3_elapsed / 60))m $((step3_elapsed % 60))s"
[[ $REINIT -eq 1 ]] && echo "    (three-pass: run → reinit → rerun + anchor save)"
echo "  Step 4  (analysis):        $((step4_elapsed / 60))m $((step4_elapsed % 60))s"
echo ""
echo "  Scenarios: $PROJECT_DIR/outputs/little_prof/scenarios/"
echo "  Log:       $LOGFILE"
echo "============================================================"
