#!/bin/bash
# run_snowpack.sh — Run SNOWPACK on all Little Professor cluster .smet files.
# Generated by install.py from slopes/little_prof/slope_config.toml
#
# Usage:
#   ./run_snowpack.sh                          # full season (default dates)
#   ./run_snowpack.sh 2025-11-26 2026-04-15   # explicit start/end (YYYY-MM-DD)
#
# On first run:  each cluster gets a copy of template.sno as initial conditions.
# On reruns:     each cluster restarts from its own _res.sno (written by SNOWPACK).

# --- Paths ---
SNOWPACK_BIN=/home/caic/caic/rtsys/snowpack/exe/snowpack
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH:-}:/home/caic/caic/rtsys/snowpack/src/snowpack/lib

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
SLOPE_DIR=${SLOPE_DIR:-$REPO_DIR/snowpack/little_prof}
SMET_DIR=${SMET_DIR:-$REPO_DIR/outputs/smet}
SNOW_IN_DIR=$SLOPE_DIR/input/snow
OUTPUT_DIR=$SLOPE_DIR/output
MASTER_CFG=$REPO_DIR/slopes/little_prof/config/master_config.ini
TEMPLATE_SNO=$SNOW_IN_DIR/template.sno

# --- Date range ---
first_smet=("$SMET_DIR"/cluster_*.smet)
if [[ -n "${1:-}" ]]; then
    BDATE="${1}"
    [[ "$BDATE" != *T* ]] && BDATE="${BDATE}T18:00"
else
    BDATE=$(awk '/^\[DATA\]/{found=1; next} found{print $1; exit}' "${first_smet[0]}")
fi
EDATE="${2:-2026-03-31}T18:00"

# Optional: run only specific clusters (plain text or reinit_stats JSON)
CLUSTERS_FILE="${3:-}"

MAX_JOBS=30

# --- Sanity checks ---
for f in "$SNOWPACK_BIN" "$MASTER_CFG" "$TEMPLATE_SNO"; do
    if [[ ! -f "$f" ]]; then
        echo "ERROR: required file not found: $f" >&2
        exit 1
    fi
done

smets=( "$SMET_DIR"/cluster_*.smet )
if [[ ${#smets[@]} -eq 0 ]]; then
    echo "ERROR: no cluster .smet files found in $SMET_DIR" >&2
    exit 1
fi

mkdir -p "$OUTPUT_DIR"

echo "=== Little Professor SNOWPACK run ==="
echo "    Start:    $BDATE"
echo "    End:      $EDATE"
echo "    Clusters: ${#smets[@]}"
[[ -n "$CLUSTERS_FILE" ]] && echo "    Filter:   $CLUSTERS_FILE"
echo "    Started:  $(date -u)"
echo ""

# Build cluster filter set (if provided)
declare -A CLUSTER_FILTER
if [[ -n "$CLUSTERS_FILE" && -f "$CLUSTERS_FILE" ]]; then
    if [[ "$CLUSTERS_FILE" == *.json ]]; then
        while IFS= read -r cid_num; do
            CLUSTER_FILTER["cluster_$(printf '%04d' "$cid_num")"]=1
        done < <(python3 -c "
import json, sys
with open('$CLUSTERS_FILE') as f:
    data = json.load(f)
for item in data:
    print(item['cid'])
")
    else
        while IFS= read -r line; do
            CLUSTER_FILTER["$line"]=1
        done < "$CLUSTERS_FILE"
    fi
    echo "    Filtered to ${#CLUSTER_FILTER[@]} clusters"
fi

for smet in "${smets[@]}"; do
    cid=$(basename "$smet" .smet)
    if [[ ${#CLUSTER_FILTER[@]} -gt 0 && -z "${CLUSTER_FILTER[$cid]:-}" ]]; then
        continue
    fi

    lat=$(awk -F'=' '/^latitude/{gsub(/ /,"",$2); print $2}' "$smet")
    lon=$(awk -F'=' '/^longitude/{gsub(/ /,"",$2); print $2}' "$smet")
    alt=$(awk -F'=' '/^altitude/{gsub(/ /,"",$2); print $2}' "$smet")

    res_sno="$OUTPUT_DIR/${cid}_${cid}.sno"
    cluster_sno="$SNOW_IN_DIR/${cid}.sno"
    if [[ -f "$res_sno" ]]; then
        cp "$res_sno" "$cluster_sno"
    else
        sed -e "s/WRFPT/$cid/g"  \
            -e "s/WRFNAME/$cid/g" \
            -e "s/WRFLAT/$lat/g"  \
            -e "s/WRFLON/$lon/g"  \
            -e "s/WRFELEV/$alt/g" \
            -e "s/WRFDATE/${BDATE%T*}/g" \
            "$TEMPLATE_SNO" > "$cluster_sno"
    fi

    cluster_ini="$OUTPUT_DIR/${cid}.ini"
    cat > "$cluster_ini" << EOF
IMPORT_BEFORE = $MASTER_CFG

[Input]
METEOPATH  = $SMET_DIR
SNOWPATH   = $SNOW_IN_DIR
METEOFILE1 = $cid
SNOWFILE1  = $cid

[Output]
METEOPATH  = $OUTPUT_DIR
SNOWPATH   = $OUTPUT_DIR
EXPERIMENT = $cid
EOF

    "$SNOWPACK_BIN" -c "$cluster_ini" -b "$BDATE" -e "$EDATE" \
        > "$OUTPUT_DIR/${cid}.log" 2>&1 &

    ct=$(ps aux | grep "[s]nowpack.*exe" | wc -l)
    while [[ $ct -ge $MAX_JOBS ]]; do
        sleep 1
        ct=$(ps aux | grep "[s]nowpack.*exe" | wc -l)
    done
done

wait
echo "=== Run complete: $(date -u) ==="

n_ok=0; n_fail=0
for log in "$OUTPUT_DIR"/cluster_*.log; do
    if grep -q "done!" "$log" 2>/dev/null; then
        n_ok=$((n_ok + 1))
    else
        n_fail=$((n_fail + 1))
    fi
done
echo "    OK: $n_ok   Failed: $n_fail"
if [[ $n_fail -gt 0 ]]; then
    echo "    Failed clusters:"
    for log in "$OUTPUT_DIR"/cluster_*.log; do
        if ! grep -q "done!" "$log" 2>/dev/null; then
            echo "      $(basename "$log" .log)"
        fi
    done
fi

echo ""
echo "=== Aggregating results to Zarr ==="
$REPO_DIR/.venv/bin/python3 $REPO_DIR/src/avachain/build_zarr_chunked.py \
    --pro-dir "$OUTPUT_DIR" --zarr-out "$OUTPUT_DIR/slope_snowpack.zarr"
echo "=== Zarr Build Complete ==="
